import React, { useState, useEffect, useRef } from 'react';
import Head from 'next/head';
import {
  Hero,
  Menu,
  Servicios,
  Slider,
  Map,
  ContactForm,
  WhatsappButton,
  Footer
} from '@/components';
import { dataset } from '@/lib/dataset';
import useDeviceSize from '@/hooks/useDeviceSize';

export default function Home() {
  const arrayWidth = useDeviceSize();
  const width = arrayWidth[0];
  const contactRef = useRef<HTMLDivElement>(null);
  const [isMobile, setIsMobile] = useState<boolean>();

  useEffect(() => {
    if (width >= 1024) {
      setIsMobile(false);
    } else {
      setIsMobile(true);
    }
  }, [width, isMobile]);
  return (
    <>
      <Head>
        <title>GR-Soluciones Eléctricas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Menu Items={dataset.Menu.Items} showList={dataset.Menu.showList} />
        <Hero
          // imageDesktop={dataset.Hero.imageDesktop}
          // imageMobile={dataset.Hero.imageMobile}
          title={dataset.Hero.title}
          subTitle={dataset.Hero.subTitle}
          videoDesktop={dataset.Hero.videoDesktop}
          videoMobile={dataset.Hero.videoMobile}
        />

        <Servicios items={dataset.Servicios.items} />

        <Slider items={dataset.Slider.items} />

        <Map
          ubication={dataset.Map.ubication}
          title={dataset.Map.title}
          subtitle={dataset.Map.subtitle}
        />

        <div ref={contactRef}>{dataset.Contact && <ContactForm {...dataset.Contact} />}</div>
        <WhatsappButton />
        <Footer />
      </main>
    </>
  );
}
